sudo: required

language: java


stages:
  - build & test
  - sonar

jobs:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
    - jdk: oraclejdk-ea
  include:
    - stage: build & test
      jdk: openjdk10
      script:
        - "java -Xmx32m -version"
        - "./gradlew buildDependents --info"

    - stage: build & test
      jdk: openjdk-ea
      script:
        - "java -Xmx32m -version"
        - "./gradlew buildDependents --info"

    - stage: build & test
      jdk: oraclejdk-ea
      script:
        - "java -Xmx32m -version"
        - "./gradlew buildDependents --info"

    - stage: sonar
      jdk: openjdk10
      before_script:
        #for full sonar cloud blame information
        - "git fetch --unshallow"
      script:
        - "./gradlew sonarqube"
